### PR TITLE
add dependency version and chart outputs

### LINKED ISSUE #3: [Feature Request] Read chart dependencies
With Helm 3, chart dependencies are now included in the `Chart.yaml`, rather than in a separate file. Would it be possible to expose the dependencies (and their values) in this actions data structure? I'm envisioning something like this working:

```yaml
steps:
- uses: actions/checkout@master
- name: Read Helm Chart
  id: chart
  uses: jacobtomlinson/gha-read-helm-chart@master
  with:
    path: path/to/chart
- name: Print outputs
    run: |
    echo "Version - ${{ steps.chart.outputs.version }}"
    echo "Dependency Version - ${{ steps.chart.outputs.dependencies.dask.version }}"
```

### PR DESCRIPTION
**Pull request by jhamman**
closes #3

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Awesome thanks for this!

Could I ask you to update the example chart that is used in the tests with a dependency so that we can be sure this works.

https://github.com/jacobtomlinson/gha-read-helm-chart/blob/master/tests/example/Chart.yaml

**Comment by jhamman** [comment]
Done! 

Running locally, this is what I get:

```
Reading values from tests/example/Chart.yaml
::set-output name=apiVersion::v1
::set-output name=name::example
::set-output name=version::0.1.0
::set-output name=kubeVersion::
::set-output name=description::A Helm chart for Kubernetes
::set-output name=type::
::set-output name=keywords::[]
::set-output name=home::
::set-output name=sources::https://github.com/jacobtomlinson/gha-read-helm-chart
::set-output name=repository::
::set-output name=icon::
::set-output name=appVersion::1.0
::set-output name=deprecated::false
::set-output name=dependencies.example-dep.version::0.2.0
::set-output name=dependencies.example-dep.repository::https://example.com/charts/example-dep
```

**Comment by jacobtomlinson** [comment]
Thanks @jhamman. LGTM. The failing test is a bug in the tests setup as it is using the master branch instead of the PR.

**Comment by jhamman** [comment]
Actually, I'm pretty sure this is a real problem: https://github.com/jacobtomlinson/gha-read-helm-chart/actions/runs/58199358

In https://help.github.com/en/actions/building-actions/metadata-syntax-for-github-actions#outputs, it says:

> `outputs.<output_id>`
>
> Required A string identifier to associate with the output. The value of `<output_id>` is a map of the output's metadata. The `<output_id>` must be a unique identifier within the outputs object. The `<output_id>` must start with a letter or `_` and contain only alphanumeric characters, `-`, or `_`.

I take this to mean that we can't use periods (`.`) to delimitate output keys. Thoughts on `-` vs. `_`?

**Comment by jacobtomlinson** [comment]
Gah! Yeah it does look that way. My preference would probably be underscores, but that isn't really based on anything.

**Pull request merged**
